services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - docker_fintech
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "loan-request:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_fintech
#  api:
#    image: api:0.0.1
#    container_name: api
#    ports:
#      - "80:80"
#    networks:
#      - fintech
#  consumer:
#    image: consumer:0.0.1
#    container_name: consumer
#    ports:
#      - "8080:8080"
#    networks:
#      - fintech
#  css:
#    image: css:0.0.1
#    container_name: css
#    ports:
#      - "8081:8081"
#    networks:
#      - fintech
#  nginx:
#    image: nginx:0.0.1
#    container_name: nginx
#    ports:
#      - "8085:8085"
#    networks:
#      - fintech

networks:
  docker_fintech:
    driver: bridge
    external: true