version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - docker_fintech

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_fintech
  api:
    image: api:0.0.1
    container_name: api
    ports:
      - "80:80"
    networks:
      - fintech
  consumer:
    image: consumer:0.0.1
    container_name: consumer
    ports:
      - "8080:8080"
    networks:
      - fintech
  css:
    image: css:0.0.1
    container_name: css
    ports:
      - "8081:8081"
    networks:
      - fintech
  nginx:
    image: nginx:0.0.1
    container_name: nginx
    ports:
      - "8085:8085"
    networks:
      - fintech

networks:
  docker_fintech:
    driver: bridge
    external: true